from os import environ

CONNECTOR_PROXY_WAKU_BASE_URL = environ.get("CONNECTOR_PROXY_WAKU_BASE_URL", default="http://localhost:8545")

CONNECTOR_PROXY_XERO_CLIENT_ID = environ.get("CONNECTOR_PROXY_XERO_CLIENT_ID")
CONNECTOR_PROXY_XERO_CLIENT_SECRET = environ.get("CONNECTOR_PROXY_XERO_CLIENT_SECRET")

CONNECTOR_PROXY_POSTGRESQL_DB_NAME = environ.get("CONNECTOR_PROXY_POSTGRESQL_DB_NAME", default="spiffworkflow_secondary_storage_dev")
CONNECTOR_PROXY_POSTGRESQL_USER_NAME = environ.get("CONNECTOR_PROXY_POSTGRESQL_USER_NAME", default="postgres")
CONNECTOR_PROXY_POSTGRESQL_HOST = environ.get("CONNECTOR_PROXY_POSTGRESQL_HOST", default="localhost")
CONNECTOR_PROXY_POSTGRESQL_PORT = environ.get("CONNECTOR_PROXY_POSTGRESQL_PORT", default="7005")
CONNECTOR_PROXY_POSTGRESQL_PASSWORD = environ.get("CONNECTOR_PROXY_POSTGRESQL_PASSWORD")
